spring.application.name=fruitshopping

# ==================== SERVER ====================
server.port=8080

# ==================== SQL SERVER ====================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=fruitshopping;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==================== JPA / HIBERNATE ====================
# update = tạo bảng mới nếu chưa có, bỏ qua bảng đã tồn tại (WARN không phải ERROR)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

# ==================== JWT ====================
jwt.secret=fruitshopping-super-secret-jwt-key-2025-secure-minimum-256-bits-ok
jwt.expiration=604800000

# ==================== EMAIL (Gmail SMTP) ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luonghuuminhlc@gmail.com
spring.mail.password=eopy djbf vrye vtgi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

# App name (dùng trong email)
app.name=FruitFresh
app.url=http://localhost:8080

# ==================== STATIC RESOURCES ====================
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# ==================== MULTIPART FILE UPLOAD ====================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB



# ==================== VNPAY SANDBOX ====================
vnpay.tmnCode=9ZCEX1KH
vnpay.hashSecret=A87FF34DC362C4F8C3483DC6F4CF0935
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/payment/vnpay/return




